# Use an official Python runtime as a parent image
FROM python:3.6.8

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
VOLUME . /app

# Install any needed packages
RUN pip install -r requirements.txt
RUN apt-get install curl

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.6.0/wait /wait
RUN chmod +x /wait

CMD /wait && python -u app.py

EXPOSE 5000