"""empty message

Revision ID: 6d8f23f4db18
Revises: 
Create Date: 2019-12-15 00:13:26.490761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d8f23f4db18'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('count_marks', sa.Integer(), nullable=True))
    op.add_column('book', sa.Column('rating', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'rating')
    op.drop_column('book', 'count_marks')
    # ### end Alembic commands ###
